language: node_js
node_js:
  - "8.12.0"
services:
  - mysql
  - redis-server
install:
  - yarn install
env:
  - MYSQL_USER: travis
  - MYSQL_DATABASE: ketchup
  - MYSQL_HOST: localhost
script:
  - yarn run lint
  - yarn run coverage
after_script:
  - yarn global add codecov
  - yarn run report-coverage
before_install:
  - mysql -e 'CREATE DATABASE ketchup;'
