version: '3.1'

services:
  redis-server:
    hostname: redis-server
    image: redis:5-alpine
    ports:
      - "6379:6379"

  db-server:
    hostname: db-server
    image: mariadb
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ketchup
    networks:
      - ketchup

  ketchup-server:
    hostname: ketchup-server
    image: node:8.12-alpine
    restart: always
    command: sh /usr/src/app/start.sh
    ports:
      - 8001:8080
    volumes:
      - ./:/usr/src/app
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_USER=root
      - MYSQL_HOST=db-server
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=ketchup
    links:
      - db-server
      - redis-server
    networks:
      - ketchup

networks:
  ketchup:
    driver: bridge
